### ISSUE TITLE
[BUG]Latest version is missing on marketplace

### ISSUE THREAD

**Issue by ZoranPandovski** [contributor-assistant/github-action#108]
**Describe the bug**

The latest v2.0.0 is not published on the marketplace.

**To Reproduce**
1. Upgrade to the v2.0.0 version
2. Unable to resolve action `contributor-assistant/github-action@v2.0.0`, unable to find version `v2.0.0` is thrown.

**Comment by ibakshay** [comment]
Hi @ZoranPandovski, 
Thank you for raising this issue. I have now published another new patch version that is also published on GitHub market place -  https://github.com/marketplace/actions/cla-assistant-lite.
