### ISSUE TITLE
[BUG] Unexpected end of JSON input

### ISSUE THREAD

**Issue by jsoref** [contributor-assistant/github-action#110]
**Describe the bug**
`Unexpected end of JSON input`

**To Reproduce**

1. Create a PR to a project
https://github.com/AlexRogalskiy/java-patterns/actions/runs/2903651345/workflow
https://github.com/AlexRogalskiy/java-patterns/runs/7951029716?check_suite_focus=true

```
Run cla-assistant/github-action@v2.1.3-beta
  with:
    path-to-signatures: cla/signatures.json
    path-to-document: https://github.com/AlexRogalskiy/java-patterns/blob/master/cla/README.md
    branch: master
    allowlist: imgbot,dependabot*
    use-dco-flag: false
    lock-pullrequest-aftermerge: true
  env:
    GITHUB_TOKEN: ***
    PERSONAL_ACCESS_TOKEN: ***
CLA Assistant GitHub Action bot has started the process
Error: Unexpected end of JSON input
```

**Expected behavior**
Error messages should be easily understood by humans, not just underlying technical details. They should be specific, so if a certain file is malformed, the name of the file should be indicated.

Note: if your software can _know_ it's an alpha/beta and can _know_ that there's a released version available for the same (or newer), then it _might_ make sense to warn and suggest updating (I haven't done this yet for my own software, but it came up this weekend, so I'm considering it).

**Screenshots**

**Comment by ibakshay** [comment]
Hi @jsoref,
Thanks a lot for creating this issue. 
I am sorry for the late response! 
I have fixed this issue in the above PR :)
