### ISSUE TITLE
[Feature] Upgrade Node.js

### ISSUE THREAD

**Issue by tovbinm** [contributor-assistant/github-action#118]
**Is your feature request related to a problem? Please describe.**
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 

**Describe the solution you'd like**
Please update a newer version, e.g Node.js 16

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by artemrys** [comment]
Created a PR to address the update to Node 16 here: #120

**Comment by ibakshay** [comment]
Handled in this PR https://github.com/contributor-assistant/github-action/pull/126 😄
