### ISSUE TITLE
[Q] allow `renovate`

### ISSUE THREAD

**Issue by unional** [contributor-assistant/github-action#119]
I want to allow `renovate` bot to skip CLA but not using the `bot*` which I think is too board.

I have tried `allowlist: renovate` and `allowlist: renovate[bot]` both doesn't work.

What is the right value?

**Comment by ibakshay** [comment]
Hi @unional,
`allowlist: renovate[bot] `should work for you. 
@laurent22, I have noticed that you have added `renovate[bot]` in your [project](https://github.com/laurent22/joplin/blob/ad8947a85d3ec24ef5f3d7e4bfd8cad571898f82/.github/workflows/cla.yml#L25). Could you please confirm if it works for you?

**Comment by unional** [comment]
Yes. I think it is working now. That was a while back so I am can't remember what or when it starts working.

**Comment by laurent22** [comment]
I confirm it works for me too
