### ISSUE TITLE
Discontinued project?

### ISSUE THREAD

**Issue by laurent22** [contributor-assistant/github-action#132]
I'm wondering what's the status of this project? Unfortunately we are completely dependent on it, and all our pull requests are now broken due to a bug (https://github.com/contributor-assistant/github-action/issues/131). And given that there's no answer to any of the recent issues, I'm not hopeful we'll get any answer either.

Just wondering it the owner could clarify the status? Is that a bot we can rely on for production software, or is it more or less discontinued?

**Comment by ibakshay** [comment]
Hi @laurent22,
I am sorry for the late response. I am a single project maintainer and I maintain this project outside my working hours. So, sometimes you might see a delay in my response but this project is very much up-to-date. Feel free to support this project by creating PRs and I will be more than happy to review and accept your contribution. Thank you for already creating one PR 🚀.

**Comment by laurent22** [comment]
Thanks for confirming @ibakshay. I definitely understand the difficulty in maintaining an open source project, and if it had been discontinued that would have been fine of course, but fact that it's not is great!

By the way, is there any way to donate?

**Comment by ibakshay** [comment]
Hi @laurent22,
Thank you very much and I very much appreciate it! 
You can sponsor me via [Github sponsor](https://github.com/sponsors/ibakshay).
