### ISSUE TITLE
[BUG] "Error: Unable to locate this workflow's ID in this repository, can't trigger job.."

### ISSUE THREAD

**Issue by darrellwarde** [contributor-assistant/github-action#135]
**Describe the bug**

When triggering off a `pull_request_target` event, the GitHub Action successfully looks up the signature of the committer, but then fails with error "Unable to locate this workflow's ID in this repository, can't trigger job..". This renders the status of the commit as failed and blocks merging of the PR.

I suspect that `pull_request_target` may need adding to this check in addition to `pull_request`: https://github.com/contributor-assistant/github-action/blob/6b4d5669b080c774326224fb6c823ed012c3e8ad/src/pullRerunRunner.ts#L8

**To Reproduce**

1. Trigger the GHA using `pull_request_target` as instructed in the README
2. Open a PR, sign, and you will experience this error

**Expected behavior**

The status check passes because all committers have signed the CLA.

**Comment by TGTGamer** [comment]
Replicated. 

Action Run (With debug): https://github.com/Eventiva/Eventiva/actions/runs/4910833824/jobs/8768378043#step:2:54

**Comment by darrellwarde** [comment]
Please see #139 for the fix to the actual issue in play here.
