### ISSUE TITLE
[Feature] Upgrade to Node 20

### ISSUE THREAD

**Issue by leondz** [contributor-assistant/github-action#149]
**Is your feature request related to a problem? Please describe.**
contributor-assistant uses a deprecated version of Node (see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Describe the solution you'd like**
Would like contributor-assistant to use Node 20

**Comment by ibakshay** [comment]
Hi @leondz, 
Thanks a lot. I will upgrade and do a new release within a week. Let us keep this issue till then.

**Comment by kingthorin** [comment]
It's been about 15 weeks. Any news?

**Comment by ibakshay** [comment]
> It's been about 15 weeks. Any news?

Node has been upgarded with the [latest release](https://github.com/contributor-assistant/github-action/releases/tag/v2.5.0). I apologise for a LONG delay.

Please update the version of `contributor-assistant/github-action` to `v2.5.0` in your repository.

**Comment by kingthorin** [comment]
Great, thank you!! 😊

**Comment by kingthorin** [comment]
Uh oh, looks like you updated CI but still left the action using 16:
https://github.com/contributor-assistant/github-action/blob/288ded2bc5a0f48314232cffa20ff7314a34b8ce/action.yml#L42

**Comment by ibakshay** [comment]
> @ibakshay Uh oh, looks like you updated CI but still left the action using 16:
> 
> https://github.com/contributor-assistant/github-action/blob/288ded2bc5a0f48314232cffa20ff7314a34b8ce/action.yml#L42

Great catch! 
I did a quick patch and released a new version now :) 
https://github.com/contributor-assistant/github-action/releases/tag/v2.5.1

**Comment by kingthorin** [comment]
Thanks!
