### ISSUE TITLE
[QUESTION] why do we need to store the signatures in the repo?

### ISSUE THREAD

**Issue by sumanth-lingappa** [contributor-assistant/github-action#151]
continuing #150 

there is a `path-to-signatures` attribute to this action, which stores the signature details of the contributor.

**Why do we need to store the signature details in our repo?** 

My branch is protected and this workflow keeps failing.

**Comment by ibakshay** [comment]
closing as this issue is duplicate of https://github.com/contributor-assistant/github-action/issues/150

**Comment by sumanth-lingappa** [comment]
I need to understand why do we need to store the CLA signatures in the repo?
