### ISSUE TITLE
Transfer Ownership to SAP org - https://github.com/sap

### ISSUE THREAD

**Issue by michael-spengler** [contributor-assistant/github-action#79]
1. rename repo from "github-action" to "contributor assistant" (check with branding colleagues - same logo different color.. https://www.sapbrandtools.com/naming-center/#/dashboard)
2. check legal prerequisites (maintainers... / [internal checklist](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?spaceKey=ospodocs&title=Create+an+SAP+Open+Source+Project))

**Comment by michael-spengler** [comment]
![Screenshot 2021-04-07 at 11 08 34](https://user-images.githubusercontent.com/43786652/113841113-accb7880-9791-11eb-9d83-9ec6b2f77d4d.png)

**Comment by jsoref** [comment]
This goes against GitHub's recommendations wrt renaming repositories:
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

> Note: GitHub will not redirect calls to an action hosted by a renamed repository. Any workflow that uses that action will fail with the error repository not found. Instead, create a new repository and action with the new name and archive the old repository. For more information, see "[Archiving repositories](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)."
